### ISSUE TITLE
Plugin locks up IDEA

### ISSUE THREAD

**Issue by CrazyCoder** [aicodes/idea-plugin#3]
https://youtrack.jetbrains.com/issue/IDEA-168817

```
"ApplicationImpl pooled thread 38" #648 prio=4 os_prio=-1 tid=0x000000003059d800 nid=0x1878 runnable [0x000000004635d000]
   java.lang.Thread.State: RUNNABLE
    at java.io.FileOutputStream.$$YJP$$writeBytes(Native Method)
    at java.io.FileOutputStream.writeBytes(FileOutputStream.java)
    at java.io.FileOutputStream.write(FileOutputStream.java:326)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    - locked <0x00000000d4ea6b20> (a java.io.BufferedOutputStream)
    at java.io.PrintStream.write(PrintStream.java:482)
    - locked <0x00000000d4e0e620> (a java.io.PrintStream)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
    at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
    - locked <0x00000000d4ea6b38> (a java.io.OutputStreamWriter)
    at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
    at java.io.PrintStream.write(PrintStream.java:527)
    - eliminated <0x00000000d4e0e620> (a java.io.PrintStream)
    at java.io.PrintStream.print(PrintStream.java:669)
    at java.io.PrintStream.println(PrintStream.java:823)
    - locked <0x00000000d4e0e620> (a java.io.PrintStream)
    at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:748)
    at java.lang.Throwable.printStackTrace(Throwable.java:658)
    - locked <0x00000000d4e0e620> (a java.io.PrintStream)
    at java.lang.Throwable.printStackTrace(Throwable.java:643)
    at java.lang.Throwable.printStackTrace(Throwable.java:634)
    at codes.ai.localapi.ApiClient.pokeLocalAiServer(ApiClient.java:175)
    at codes.ai.localapi.ApiClient.tryGetSimilarityFromAI(ApiClient.java:138)
    at codes.ai.localapi.ApiClient.getMethodWeight(ApiClient.java:96)
    at codes.ai.ep.AiWeigher.weigh(AiWeigher.java:27)
    at codes.ai.ep.AiWeigher.weigh(AiWeigher.java:15)
    at com.intellij.codeInsight.completion.impl.CompletionServiceImpl$3.weigh(CompletionServiceImpl.java:258)
    at com.intellij.codeInsight.lookup.LookupElementWeigher.weigh(LookupElementWeigher.java:54)
    at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:90)
    at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:34)
    at com.intellij.codeInsight.lookup.Classifier.addElement(Classifier.java:39)
    at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:102)
    at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:34)
    at com.intellij.codeInsight.lookup.Classifier.addElement(Classifier.java:39)
    at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:102)
    at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:34)
    at com.intellij.codeInsight.lookup.Classifier.addElement(Classifier.java:39)
    at com.intellij.codeInsight.completion.impl.LiftShorterItemsClassifier.addElement(LiftShorterItemsClassifier.java:72)
    at com.intellij.codeInsight.completion.impl.LiftShorterItemsClassifier.addElement(LiftShorterItemsClassifier.java:38)
    at com.intellij.codeInsight.lookup.Classifier.addElement(Classifier.java:39)
    at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:102)
    at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:34)
    at com.intellij.codeInsight.lookup.Classifier.addElement(Classifier.java:39)
    at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:102)
    at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:34)
    at com.intellij.codeInsight.lookup.Classifier.addElement(Classifier.java:39)
    at com.intellij.codeInsight.completion.impl.LiftShorterItemsClassifier.addElement(LiftShorterItemsClassifier.java:72)
    at com.intellij.codeInsight.completion.impl.LiftShorterItemsClassifier.addElement(LiftShorterItemsClassifier.java:38)
    at com.intellij.codeInsight.completion.CompletionLookupArranger.addElement(CompletionLookupArranger.java:159)
    at com.intellij.codeInsight.lookup.impl.LookupImpl.a(LookupImpl.java:258)
    at com.intellij.codeInsight.lookup.impl.LookupImpl$$Lambda$2492/1920308361.compute(Unknown Source)
    at com.intellij.codeInsight.lookup.impl.LookupImpl.a(LookupImpl.java:1175)
    - locked <0x00000000dc6dc858> (a java.lang.Object)
    at com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(LookupImpl.java:256)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:415)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItem(CompletionProgressIndicator.java:406)
    at com.intellij.codeInsight.completion.AsyncCompletion$1.a(CompletionThreading.java:136)
    at com.intellij.codeInsight.completion.AsyncCompletion$1$$Lambda$2487/987359619.compute(Unknown Source)
    at com.intellij.codeInsight.completion.AsyncCompletion$1WeighItems.run(CompletionThreading.java:107)
    at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:87)
    at com.intellij.codeInsight.completion.AsyncCompletion$$Lambda$2447/2019878544.run(Unknown Source)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:903)
    at com.intellij.codeInsight.completion.AsyncCompletion.b(CompletionThreading.java:84)
    at com.intellij.codeInsight.completion.AsyncCompletion$$Lambda$2446/435304555.run(Unknown Source)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
    at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$70/1355991786.run(Unknown Source)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
    at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:82)
    at com.intellij.codeInsight.completion.AsyncCompletion$$Lambda$2445/1328650765.run(Unknown Source)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
 
"AWT-EventQueue-0 2017.1#IU-171.3566.24 IDEA, eap:true, os:Windows 7 6.1, java-version:JetBrains s.r.o 1.8.0_112-release-724-b6" #29 prio=6 os_prio=0 tid=0x000000001a1e7800 nid=0x1d24 waiting for monitor entry [0x000000001ef3d000]
   java.lang.Thread.State: BLOCKED (on object monitor)
    at com.intellij.codeInsight.lookup.impl.LookupImpl.a(LookupImpl.java:1174)
    - waiting to lock <0x00000000dc6dc858> (a java.lang.Object)
    at com.intellij.codeInsight.lookup.impl.LookupImpl.getItems(LookupImpl.java:309)
    at com.intellij.codeInsight.lookup.impl.LookupImpl.resort(LookupImpl.java:231)
    at com.intellij.codeInsight.lookup.impl.LookupUi.d(LookupUi.java:222)
    at com.intellij.codeInsight.lookup.impl.LookupUi.<init>(LookupUi.java:114)
    at com.intellij.codeInsight.lookup.impl.LookupImpl.showLookup(LookupImpl.java:682)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.h(CompletionProgressIndicator.java:351)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$000(CompletionProgressIndicator.java:92)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator$1.run(CompletionProgressIndicator.java:104)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
    at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
    at com.intellij.util.ui.update.MergingUpdateQueue$$Lambda$638/824889767.run(Unknown Source)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2621)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:288)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
    at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
    at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:827)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by xuy** [comment]
Acknowledged! Will take a look ASAP. Thanks for reporting.
